# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SocialBurdenCalculator
                                 A QGIS plugin
 This plugin calculates social burden
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-30

        email                : oehart@sandia.gov
        git sha              : $Format:%H$
 ***************************************************************************/


 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SocialBurdenCalculator class from file SocialBurdenCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .social_burden_calculator import SocialBurdenCalculator
    return SocialBurdenCalculator(iface)
